apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-fluentbit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent/fluent-bit
    targetRevision: 0.19.19
  helm:    
    valuesFile: ['values.yaml']
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:  
      prune: true    