apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-fluentbit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent/fluent-bit
    targetRevision: 1.8.12
    helm:    
      valueFiles: 
        - values-${ARGOCD_APP_NAMESPACE}.yaml
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:  
      prune: true    