apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-redis
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 16.4.5
    helm:
      valueFiles:
        - values.yaml
    chart: redis 
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:  
      prune: true    